### ISSUE TITLE
Feedback for code quality of A0158963M

### ISSUE THREAD

**Issue by nishantbudhdev** [CS2103AUG2016-T15-C3/main#108]
* Indentation problem here. Our coding standard requires you to use 4 spaces instead of tabs. You can configure Eclipse to convert tabs to spaces automatically.
<img width="512" alt="screen shot 2016-10-31 at 9 36 18 pm" src="https://cloud.githubusercontent.com/assets/956015/19855943/2d540364-9fb2-11e6-990c-c284a89b070f.png">
* The header comments, name of the method and the method code don't match.
<img width="528" alt="screen shot 2016-10-31 at 9 37 44 pm" src="https://cloud.githubusercontent.com/assets/956015/19855984/6c13db88-9fb2-11e6-8448-cc884023d4c3.png">

Please check the [PR](https://github.com/nus-cs2103-AY1617S1/addressbook-level4/pull/202) for more comments.

**Comment by tyrahuang** [comment]
Sorry, I don't understand "name of the method and the method code don't match".
Should I change the method name prepareSetstorage to confirmStorageLocation something like that?
Thanks
